name: Build and Deploy to Skynet

on:
  push:
    tags:
      - v[12].[0-9]+.[0-9]+

env:
  FORCE_COLOR: 2

jobs:
  build:
    name: Build and Deploy to Skynet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
      - name: Deploy to Skynet
        uses: SkynetLabs/deploy-to-skynet-action@v2.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          registry-datakey: "${{ secrets.REGISTRY_DATAKEY || '' }}"
          registry-seed: "${{ secrets.REGISTRY_SEED || '' }}"
          upload-dir: dist