name: Testing and Versioning 

on:
  push:
    branches:
      - "**" 
  pull_request:
    branches:
      - main

env:
  FORCE_COLOR: 2

jobs:
  release:
    name: Versioning and possible release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn install
      - name: Prettier Check
        run: yarn lint-check
      - name:  Jest Tests
        run: yarn test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: 0
        run: npx semantic-release
